// data/projects.ts

export const projects = [
    {
      id: 1,
      name: "Skyline Towers",
      contractor: "BuildIt Inc.",
      address: "123 Main St, City Center",
      status: "Ongoing",
      tests: [
        { name: "Soil Compaction Test", passed: true },
        { name: "Concrete Strength Test", passed: false },
        { name: "Electrical Safety Test", passed: true },
        { name: "Waterproofing Test", passed: true },
        { name: "Fire Resistance Test", passed: false },
      ],
      laborDetails: {
        daysWorked: 120,
        totalWages: 50000,
        hourlyWages: 20,
        numberOfLabors: 25,
      },
    },
    {
      id: 2,
      name: "Seaside Villas",
      contractor: "Ocean View Constructions",
      address: "456 Beach Rd, Seaside Town",
      status: "Completed",
      tests: [
        { name: "Soil Compaction Test", passed: true },
        { name: "Concrete Strength Test", passed: true },
        { name: "Electrical Safety Test", passed: true },
        { name: "Waterproofing Test", passed: true },
        { name: "Fire Resistance Test", passed: true },
      ],
      laborDetails: {
        daysWorked: 180,
        totalWages: 75000,
        hourlyWages: 25,
        numberOfLabors: 30,
      },
    },
    {
      id: 3,
      name: "Urban Heights",
      contractor: "Cityscape Builders",
      address: "789 Uptown Blvd, Downtown District",
      status: "Ongoing",
      tests: [
        { name: "Soil Compaction Test", passed: true },
        { name: "Concrete Strength Test", passed: true },
        { name: "Electrical Safety Test", passed: false },
        { name: "Waterproofing Test", passed: false },
        { name: "Fire Resistance Test", passed: true },
      ],
      laborDetails: {
        daysWorked: 90,
        totalWages: 45000,
        hourlyWages: 22,
        numberOfLabors: 20,
      },
    },
    {
      id: 4,
      name: "Green Meadows",
      contractor: "EcoBuild Corp",
      address: "101 Green St, Eco Village",
      status: "Planned",
      tests: [
        { name: "Soil Compaction Test", passed: false },
        { name: "Concrete Strength Test", passed: false },
        { name: "Electrical Safety Test", passed: true },
        { name: "Waterproofing Test", passed: false },
        { name: "Fire Resistance Test", passed: false },
      ],
      laborDetails: {
        daysWorked: 60,
        totalWages: 32000,
        hourlyWages: 18,
        numberOfLabors: 15,
      },
    },
    {
      id: 5,
      name: "Mountain View Apartments",
      contractor: "Peak Constructions",
      address: "202 Highland Ave, Mountain Region",
      status: "Ongoing",
      tests: [
        { name: "Soil Compaction Test", passed: true },
        { name: "Concrete Strength Test", passed: true },
        { name: "Electrical Safety Test", passed: true },
        { name: "Waterproofing Test", passed: true },
        { name: "Fire Resistance Test", passed: true },
      ],
      laborDetails: {
        daysWorked: 200,
        totalWages: 100000,
        hourlyWages: 30,
        numberOfLabors: 35,
      },
    },
    {
      id: 6,
      name: "Riverfront Plaza",
      contractor: "WaterEdge Builders",
      address: "303 Riverside Dr, River City",
      status: "Completed",
      tests: [
        { name: "Soil Compaction Test", passed: true },
        { name: "Concrete Strength Test", passed: true },
        { name: "Electrical Safety Test", passed: true },
        { name: "Waterproofing Test", passed: true },
        { name: "Fire Resistance Test", passed: true },
      ],
      laborDetails: {
        daysWorked: 240,
        totalWages: 120000,
        hourlyWages: 28,
        numberOfLabors: 40,
      },
    },
    {
      id: 7,
      name: "Downtown Mall",
      contractor: "City Square Construction",
      address: "404 Central Ave, Downtown",
      status: "Ongoing",
      tests: [
        { name: "Soil Compaction Test", passed: true },
        { name: "Concrete Strength Test", passed: true },
        { name: "Electrical Safety Test", passed: false },
        { name: "Waterproofing Test", passed: true },
        { name: "Fire Resistance Test", passed: true },
      ],
      laborDetails: {
        daysWorked: 300,
        totalWages: 150000,
        hourlyWages: 26,
        numberOfLabors: 45,
      },
    },
  ];
  